FROM node:20-bookworm-slim

RUN apt-get update && apt-get install -y \
    g++ \
    python3 \
    default-jdk \
    coreutils \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace

CMD ["sleep", "infinity"]